// <auto-generated />
namespace LearningWebsite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class user_pass_not_required_temp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(user_pass_not_required_temp));
        
        string IMigrationMetadata.Id
        {
            get { return "201603151944194_user_pass_not_required_temp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
