// <auto-generated />
namespace LearningWebsite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ignore_isValid_user : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ignore_isValid_user));
        
        string IMigrationMetadata.Id
        {
            get { return "201603151939511_ignore_isValid_user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
