// <auto-generated />
namespace LearningWebsite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_course_material_ratings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_course_material_ratings));
        
        string IMigrationMetadata.Id
        {
            get { return "201603191804047_add_course_material_ratings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
