// <auto-generated />
namespace LearningWebsite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adding_coursematerial_title_required : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adding_coursematerial_title_required));
        
        string IMigrationMetadata.Id
        {
            get { return "201603161439265_adding_coursematerial_title_required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
