// <auto-generated />
namespace LearningWebsite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class discussion_board_timestamp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(discussion_board_timestamp));
        
        string IMigrationMetadata.Id
        {
            get { return "201604190049578_discussion_board_timestamp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
